CREATE SEQUENCE IF NOT EXISTS PUBLIC.USER_SEQ;

CREATE TABLE IF NOT EXISTS PUBLIC.User (
   id INT AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL UNIQUE,
   created_on DATE NOT NULL
);